---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version
