---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: {{host}}
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version
